import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { expect, it, vi } from "vitest";
import {
  bundleGeneratedAssets,
  GENERATED_MODEL_MANIFEST,
} from "../src/lib/generated-bundle";
import {
  blankProject,
  generatedGeometrySchema,
  type Project,
} from "../src/lib/protocol";
import { encodeWorld, decodeWorld, exportWorld } from "../src/lib/export";
import type { GeneratedModel } from "../src/lib/generated-models";
const fixture = new Uint8Array(
  readFileSync("public/models/kenney/nature-kit/tree_default.glb"),
);
function model(glb = fixture): GeneratedModel {
  return {
    glb,
    metadata: {
      version: 1,
      source: "local-blender",
      sha256: createHash("sha256").update(glb).digest("hex"),
      bytes: glb.byteLength,
      blenderVersion: "4.0.2",
      bounds: { min: [-1, 0, -1], max: [1, 2, 1] },
      createdAt: "2026-09-08T00:00:00Z",
    },
  };
}
function project(models: GeneratedModel[]): Project {
  return {
    ...blankProject(),
    entities: models.map((record, index) => ({
      id: `model-${index}`,
      label: "Model",
      position: [0, 0, 0],
      scale: [1, 1, 1],
      color: "#ffffff",
      stage: "ready",
      geometry: generatedGeometrySchema.parse({
        kind: "generated",
        job: {
          version: 1,
          parts: [{ id: "body", shape: "box", color: "#ffffff" }],
        },
        model: record.metadata,
      }),
    })),
  };
}
it("bundles exact local GLB bytes once per hash and a sorted metadata manifest", async () => {
  const record = model();
  const read = vi.fn(async () => record);
  const files = await bundleGeneratedAssets(project([record, record]), read);
  expect(read).toHaveBeenCalledTimes(1);
  expect(Object.keys(files)).toHaveLength(2);
  expect(files[`models/generated/${record.metadata.sha256}.glb`]).toEqual(
    fixture,
  );
  expect(
    JSON.parse(new TextDecoder().decode(files[GENERATED_MODEL_MANIFEST])),
  ).toEqual({ version: 1, models: [record.metadata] });
  files[`models/generated/${record.metadata.sha256}.glb`][0] = 0;
  expect(fixture[0]).not.toBe(0);
});
it("allows differing timestamps but rejects provenance conflicts, including duplicate references", async () => {
  const record = model(),
    world = project([record, record]);
  const recipe = world.entities[1].geometry;
  if (recipe?.kind !== "generated" || !recipe.model) throw Error("fixture");
  recipe.model.createdAt = "2026-09-09T00:00:00Z";
  await expect(
    bundleGeneratedAssets(world, async () => record),
  ).resolves.toBeDefined();
  recipe.model.bounds.max[1] = 999;
  await expect(
    bundleGeneratedAssets(world, async () => record),
  ).rejects.toThrow("provenance");
});
it("rejects missing, unresolved, malformed identities, and corrupted generated bytes", async () => {
  const record = model(),
    world = project([record]);
  await expect(
    bundleGeneratedAssets(world, async () => {
      throw Error("Missing local model");
    }),
  ).rejects.toThrow("Missing");
  const tampered = { ...record, glb: record.glb.slice() };
  tampered.glb[tampered.glb.length - 1] ^= 1;
  await expect(
    bundleGeneratedAssets(world, async () => tampered),
  ).rejects.toThrow("integrity");
  const badIdentity = project([
    { ...record, metadata: { ...record.metadata, sha256: "a".repeat(64) } },
  ]);
  await expect(
    bundleGeneratedAssets(badIdentity, async () => record),
  ).rejects.toThrow("integrity");
  const recipe = world.entities[0].geometry;
  if (recipe?.kind !== "generated") throw Error("fixture");
  delete recipe.model;
  await expect(
    bundleGeneratedAssets(world, async () => record),
  ).rejects.toThrow("unfinished");
  world.entities[0].stage = "coarse";
  await expect(exportWorld(world)).rejects.toThrow("unfinished");
});
function largeModel(marker: number) {
  const jsonLength = new DataView(fixture.buffer).getUint32(12, true);
  const doc = JSON.parse(
    new TextDecoder().decode(fixture.subarray(20, 20 + jsonLength)),
  );
  doc.asset.generator = `budget-test-${marker}`;
  doc.buffers[0].byteLength = 1800000;
  const json = new TextEncoder().encode(JSON.stringify(doc)),
    padded = Math.ceil(json.length / 4) * 4;
  const bytes = new Uint8Array(28 + padded + 1800000),
    view = new DataView(bytes.buffer);
  view.setUint32(0, 0x46546c67, true);
  view.setUint32(4, 2, true);
  view.setUint32(8, bytes.length, true);
  view.setUint32(12, padded, true);
  view.setUint32(16, 0x4e4f534a, true);
  bytes.fill(32, 20, 20 + padded);
  bytes.set(json, 20);
  view.setUint32(20 + padded, 1800000, true);
  view.setUint32(24 + padded, 0x004e4942, true);
  bytes.set(fixture.subarray(28 + jsonLength), 28 + padded);
  return model(bytes);
}
it("enforces per-model and aggregate byte limits with otherwise valid binary models", async () => {
  const oversized = model();
  await expect(
    bundleGeneratedAssets(project([oversized]), async () => ({
      ...oversized,
      glb: new Uint8Array(2 * 1024 * 1024 + 1),
    })),
  ).rejects.toThrow("size budget");
  const models = [0, 1, 2, 3].map(largeModel),
    byHash = new Map(models.map((record) => [record.metadata.sha256, record]));
  await expect(
    bundleGeneratedAssets(project(models), async (hash) => byHash.get(hash)!),
  ).rejects.toThrow("size budget");
});
it("blocks quick-share links for local generated geometry while preserving ordinary sharing", async () => {
  expect(() => encodeWorld(project([model()]))).toThrow("Download your world");
  const plain = blankProject();
  expect(decodeWorld(encodeWorld(plain)).entities).toEqual([]);
  const catalog: Project = {
    ...plain,
    entities: [
      {
        id: "tree",
        label: "Tree",
        position: [0, 0, 0],
        scale: [1, 1, 1],
        color: "#ffffff",
        stage: "ready",
        geometry: {
          kind: "asset",
          assetId: "kenney.nature.tree-default",
          detail: "refined",
        },
      },
    ],
  };
  expect(decodeWorld(encodeWorld(catalog)).entities).toEqual(catalog.entities);
  await expect(bundleGeneratedAssets(catalog)).resolves.toEqual({});
});
